language: generic

dist: xenial

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-6.0
  - pypy3.5-6.0

env:
  global:
    - PYTHON2_7=2.7.15
    - PYTHON3_4=3.4.9
    - PYTHON3_5=3.5.6
    - PYTHON3_6=3.6.8
    - PYTHON3_7=3.7.2

os:
  - linux
  - osx

matrix:
  allow_failures:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: pypy3.5-6.0

install:
  - export PATH=$HOME/.pyenv/shims:$PATH
  - python get_python.py
  - source .venv/bin/activate
  - pip install tox-travis tox

script:
  - tox

after_success:
  - tox -e codecov
