language: python

dist: xenial

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-6.0
  - pypy3.5-6.0

matrix:
  allow_failures:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: pypy3.5-6.0

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - tox -e codecov
