language: generic

dist: xenial

env:
  matrix:
    - PYTHON=2.7.15
    - PYTHON=3.4.9
    - PYTHON=3.5.6
    - PYTHON=3.6.8
    - PYTHON=3.7.2
    - PYTHON=pypy2.7-6.0
    - PYTHON=pypy3.5-6.0

os:
  - linux
  - osx

matrix:
  allow_failures:
    - env: PYTHON=3.4.9
    - env: PYTHON=3.5.6
    - env: PYTHON=3.6.8
    - env: PYTHON=3.7.2
    - env: PYTHON=pypy3.5-6.0

install:
  - export TRAVIS_PYTHON_VERSION=$(echo $PYTHON | sed '/^pypy/! s/.[^.]\+$//')
  - export PATH=$HOME/.pyenv/shims:$PATH
  - python get_python.py
  - source .venv/bin/activate
  - pip install tox-travis tox

script:
  - tox

after_success:
  - tox -e codecov
