language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
 - "pypy3"
matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "pypy3"
install:
  - pip install tox-travis
script:
  - tox
sudo: false
